### ISSUE TITLE
Add navigation within `papers.html`

### ISSUE THREAD

**Issue by dwtj** [lab-design/design.cs.iastate.edu#5]
The papers page is very long. We should have some way for the user to jump from the top of the page down to the Journal papers, TRs, etc. I think that ideally, this navigation element would float on the right or left side of the page as the user scrolls (at least when the window is wide enough).

**Comment by jlmaddox** [comment]
I am currently unable to get a static TOC to appear on the papers page by using markdown like it's used on the paninij site. I believe the markdown is supposed to be the following and should work by default:
`* Anything here`
`{:toc}`
But it doesn't seem to. I will probably end up having to use a javascript solution in this case. Or it could just be a hard-coded TOC.

**Comment by dwtj** [comment]
This may be a silly question, but is the problem that our `papers.html` file is an HTML file rather than a markdown file?

**Comment by jlmaddox** [comment]
Looks like that's the case, actually. Turns out to get the TOC to generate I need to 1. change the file extension and 2. change headers from `<h3>` to the `###` syntax. It does mean I need to find a new way to have extra space above the `<h3>` elements though.

**Comment by dwtj** [comment]
You could just add in a `<br />` element after each section.

Or maybe there is a markdown syntax to add the class to a `###` element.

**Comment by jlmaddox** [comment]
I currently have a TOC being generated via the above method. However, I don't see a way to style it so that it appears on the right side of the page's content. I need to surround the content of the page itself in a div to apply the col-md-9 and related bootstrap classes to this div. The problem is that any markdown inside of HTML elements is ignored, and since the markdown TOC depends on headers with the `###` format, I can't surround the page content and have it work. 

My current thoughts are to simply style the TOC a little and leave it at that for now unless we really want a TOC floated to the right of the content, in which case hardcoding it would be easiest.

**Comment by dwtj** [comment]
Ok. We don't have to worry about having the contents on the side, for now.

However, I have some qualms about the styling. When I go to the page, it seems like it takes me just a little bit too long to realize what it is. Maybe it looks too similar to the other content.

It may also be enough to just make the font in the box different somehow. Maybe smaller or narrower (i.e. the `font-weight` CSS property). 

We might also crib the styling from wikipedia TOCs. Here's an example:

![screen shot 2017-01-16 at 1 36 22 pm](https://cloud.githubusercontent.com/assets/2457848/21996641/e0ffce0a-dbf0-11e6-8cab-945d794e5467.png)

If so, I think that we would change this in a few ways:

- Add a centered/bolded "Contents" title or maybe "Jump To Section"
- Make the box narrower.
- Change the font?

These are just some ideas. We'll go with the styling that you choose.

**Comment by jlmaddox** [comment]
I changed the styling a bit so that the surrounding box fits the content rather than spanning page width and set font-weight to "lighter". Also added a header masquerading as a title so that I could get the title inside of the box in commit def18d0. I'm not entirely sure I like the styling at the moment, but it's definitely more recognizable.

**Comment by dwtj** [comment]
Yeah, I like it a lot better. Is that it on this issue for now, or are you going to keep playing with the styling?

**Comment by jlmaddox** [comment]
I think I'll go with it as-is.

**Comment by dwtj** [comment]
Ok. Closing as of commit def18d0.
